/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemGuis;

/**
 *
 * @author diego
 */
public class ConstructionState extends javax.swing.JFrame {

    /**
     * Creates new form ConstructionState
     */
    public ConstructionState() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConstructionListTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConstructionList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ConstructionListTitle.setText("Obras");
        getContentPane().add(ConstructionListTitle);
        ConstructionListTitle.setBounds(10, 20, 31, 16);

        ConstructionList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ConstructionList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 190, 80);

        jLabel1.setText("Presupuesto (Rubros y  montos)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 150, 170, 16);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 170, 190, 146);

        jLabel2.setText("Rubros con gastos en la obra");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 150, 160, 16);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(230, 170, 180, 146);

        jLabel3.setText("Gastos del rubro seleccionado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 150, 170, 16);

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList3);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(450, 170, 260, 146);

        jLabel4.setText("Códigos de colores:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 330, 120, 16);

        jTextField1.setBackground(new java.awt.Color(0, 255, 51));
        jTextField1.setText("Presupuestado y Reintegrado");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 330, 210, 20);

        jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        jTextField2.setText("Presupuestado y No Reintegrado");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(230, 360, 210, 20);

        jTextField3.setBackground(new java.awt.Color(255, 204, 102));
        jTextField3.setText("No Presupuestado y Reintegrado");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(450, 330, 210, 22);

        jTextField4.setBackground(new java.awt.Color(255, 102, 204));
        jTextField4.setText("No Presupuestado y No Reintegrado");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(450, 360, 210, 22);

        jLabel5.setText("Propietario:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 20, 80, 16);

        jLabel6.setText("Comienzo de Obra:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 50, 102, 16);

        jLabel7.setText("Total Gastado Ya Reintegrado:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 90, 170, 16);

        jLabel8.setText("Capataz:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 20, 60, 16);

        jLabel9.setText("Total Gastado:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(450, 60, 100, 16);

        jLabel10.setText("Total Gastado No Reintegrado:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 80, 180, 16);

        jLabel11.setText("Saldo:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(660, 80, 43, 16);

        jLabel12.setText("Total Presupuestado:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(240, 70, 130, 16);

        jTextField5.setBackground(new java.awt.Color(242, 242, 242));
        jTextField5.setText("0");
        jTextField5.setDisabledTextColor(new java.awt.Color(242, 242, 242));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(410, 82, 30, 20);

        jTextField6.setBackground(new java.awt.Color(242, 242, 242));
        jTextField6.setText("0");
        jTextField6.setCaretColor(new java.awt.Color(242, 242, 242));
        jTextField6.setDisabledTextColor(new java.awt.Color(242, 242, 242));
        jTextField6.setSelectionColor(new java.awt.Color(242, 242, 242));
        getContentPane().add(jTextField6);
        jTextField6.setBounds(410, 62, 30, 20);

        jTextField7.setBackground(new java.awt.Color(242, 242, 242));
        jTextField7.setText("0");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7);
        jTextField7.setBounds(550, 60, 30, 20);

        jTextField8.setBackground(new java.awt.Color(242, 242, 242));
        jTextField8.setText("0");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(620, 80, 30, 20);

        jTextField9.setBackground(new java.awt.Color(242, 242, 242));
        jTextField9.setText("0");
        getContentPane().add(jTextField9);
        jTextField9.setBounds(700, 80, 30, 20);

        setBounds(0, 0, 762, 401);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConstructionState.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConstructionState.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConstructionState.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConstructionState.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConstructionState().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ConstructionList;
    private javax.swing.JLabel ConstructionListTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
