/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemGuis;

/**
 *
 * @author diego
 */
public class registerForeman extends javax.swing.JFrame {

    /**
     * Creates new form registerForeman
     */
    public registerForeman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterForemanTitle = new javax.swing.JLabel();
        NameForemanInput = new javax.swing.JTextField();
        NameForemanLable = new javax.swing.JLabel();
        IdForemanLable = new javax.swing.JLabel();
        IdForemanInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        CellphoneForemanLabel = new javax.swing.JLabel();
        CellphoneForemanInput = new javax.swing.JTextField();
        AddForemanButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        RegisterForemanTitle.setText("Registrar Capataz");
        getContentPane().add(RegisterForemanTitle);
        RegisterForemanTitle.setBounds(16, 16, 110, 16);
        getContentPane().add(NameForemanInput);
        NameForemanInput.setBounds(20, 70, 150, 22);

        NameForemanLable.setText("Nombre:");
        getContentPane().add(NameForemanLable);
        NameForemanLable.setBounds(20, 50, 60, 16);

        IdForemanLable.setText("Cédula de Identidad:");
        getContentPane().add(IdForemanLable);
        IdForemanLable.setBounds(20, 110, 130, 16);
        getContentPane().add(IdForemanInput);
        IdForemanInput.setBounds(20, 130, 150, 22);

        jLabel4.setText("Dirección:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 50, 60, 16);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 70, 160, 22);

        CellphoneForemanLabel.setText("Celular:");
        getContentPane().add(CellphoneForemanLabel);
        CellphoneForemanLabel.setBounds(200, 110, 80, 16);
        getContentPane().add(CellphoneForemanInput);
        CellphoneForemanInput.setBounds(200, 130, 160, 22);

        AddForemanButton.setText("Add Foreman");
        AddForemanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddForemanButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddForemanButton);
        AddForemanButton.setBounds(20, 180, 110, 23);

        setBounds(0, 0, 414, 227);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void AddForemanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddForemanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddForemanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerForeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerForeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerForeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerForeman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerForeman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddForemanButton;
    private javax.swing.JTextField CellphoneForemanInput;
    private javax.swing.JLabel CellphoneForemanLabel;
    private javax.swing.JTextField IdForemanInput;
    private javax.swing.JLabel IdForemanLable;
    private javax.swing.JTextField NameForemanInput;
    private javax.swing.JLabel NameForemanLable;
    private javax.swing.JLabel RegisterForemanTitle;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
