/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemGuis;
import domain.Owner;
import javax.swing.JOptionPane;
import domain.FileManager;
/**
 *
 * @author diego
 */


public class RegisterOwner extends javax.swing.JFrame {

    public RegisterOwner() {
        initComponents();
    }

    private boolean isNumeric(String str) {
        try {
            Long.parseLong(str); // Use Long to accommodate larger numbers for IDs and cellphones
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private boolean validateInputs(String name, String id, String address, String cellphone) {
        if (name.length() < 3) {
            JOptionPane.showMessageDialog(null,
                "El nombre debe tener al menos 3 caracteres.",
                "Nombre inválido",
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (!isNumeric(id) || id.length() < 7) {
            JOptionPane.showMessageDialog(null,
                "La cédula de identidad debe contener solo números y tener al menos 7 dígitos.",
                "ID inválido",
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (address.length() < 4) {
            JOptionPane.showMessageDialog(null,
                "La dirección debe tener al menos 4 caracteres.",
                "Dirección inválida",
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (!isNumeric(cellphone) || cellphone.length() < 9) {
            JOptionPane.showMessageDialog(null,
                "El celular debe contener solo números y tener al menos 9 dígitos.",
                "Celular inválido",
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterOwnerTitle = new javax.swing.JLabel();
        NameOwnerInput = new javax.swing.JTextField();
        NameOwnerLabel = new javax.swing.JLabel();
        IdOwnerLabel = new javax.swing.JLabel();
        IdOwnerInput = new javax.swing.JTextField();
        AdressOwnerLabel = new javax.swing.JLabel();
        AddressOwnerInput = new javax.swing.JTextField();
        CellphoneOwnerLable = new javax.swing.JLabel();
        CellphoneOwnerInput = new javax.swing.JTextField();
        addOwnerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Propietario");
        setResizable(false);
        getContentPane().setLayout(null);

        RegisterOwnerTitle.setText("Registrar Propietario");
        getContentPane().add(RegisterOwnerTitle);
        RegisterOwnerTitle.setBounds(16, 16, 110, 16);

        NameOwnerInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameOwnerInputActionPerformed(evt);
            }
        });
        getContentPane().add(NameOwnerInput);
        NameOwnerInput.setBounds(20, 70, 150, 22);

        NameOwnerLabel.setText("Nombre:");
        getContentPane().add(NameOwnerLabel);
        NameOwnerLabel.setBounds(20, 50, 60, 16);

        IdOwnerLabel.setText("Cédula de Identidad:");
        getContentPane().add(IdOwnerLabel);
        IdOwnerLabel.setBounds(20, 110, 130, 16);
        getContentPane().add(IdOwnerInput);
        IdOwnerInput.setBounds(20, 130, 150, 22);

        AdressOwnerLabel.setText("Dirección:");
        getContentPane().add(AdressOwnerLabel);
        AdressOwnerLabel.setBounds(200, 50, 60, 16);

        AddressOwnerInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressOwnerInputActionPerformed(evt);
            }
        });
        getContentPane().add(AddressOwnerInput);
        AddressOwnerInput.setBounds(200, 70, 160, 22);

        CellphoneOwnerLable.setText("Celular");
        getContentPane().add(CellphoneOwnerLable);
        CellphoneOwnerLable.setBounds(200, 110, 100, 16);
        getContentPane().add(CellphoneOwnerInput);
        CellphoneOwnerInput.setBounds(200, 130, 160, 22);

        addOwnerButton.setText("Agregar");
        addOwnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOwnerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addOwnerButton);
        addOwnerButton.setBounds(20, 180, 110, 23);

        setBounds(0, 0, 414, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void AddressOwnerInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressOwnerInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressOwnerInputActionPerformed

    private void addOwnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOwnerButtonActionPerformed
          String ownerName = NameOwnerInput.getText().trim();
        String ownerId = IdOwnerInput.getText().trim();
        String ownerAddress = AddressOwnerInput.getText().trim(); // Corregido aquí
        String ownerCellphone = CellphoneOwnerInput.getText().trim();

        if (validateInputs(ownerName, ownerId, ownerAddress, ownerCellphone)) {
            Owner owner = new Owner(ownerName, ownerId, ownerAddress, ownerCellphone);
            FileManager.saveOwnerToFile(owner);

            // Debugging
            System.out.println("Data saved: " + ownerName + " " + ownerId + " " + ownerAddress + " " + ownerCellphone);
            System.out.println(owner);

            // Clear the input fields
            NameOwnerInput.setText("");
            IdOwnerInput.setText("");
            AddressOwnerInput.setText(""); // Corregido aquí
            CellphoneOwnerInput.setText("");

            JOptionPane.showMessageDialog(null,
                "Propietario guardado!",
                "Exito!",
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                "Estas faltando datos. Completar todos los datos para seguir.",
                "Faltando Datos",
                JOptionPane.WARNING_MESSAGE);
        }            
    }//GEN-LAST:event_addOwnerButtonActionPerformed

    private void NameOwnerInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameOwnerInputActionPerformed
        // TODO add your handling code here:R
    }//GEN-LAST:event_NameOwnerInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressOwnerInput;
    private javax.swing.JLabel AdressOwnerLabel;
    private javax.swing.JTextField CellphoneOwnerInput;
    private javax.swing.JLabel CellphoneOwnerLable;
    private javax.swing.JTextField IdOwnerInput;
    private javax.swing.JLabel IdOwnerLabel;
    private javax.swing.JTextField NameOwnerInput;
    private javax.swing.JLabel NameOwnerLabel;
    private javax.swing.JLabel RegisterOwnerTitle;
    private javax.swing.JButton addOwnerButton;
    // End of variables declaration//GEN-END:variables
}
