package systemGuis;


import domain.ConstructionsManagementSystem;
import domain.Foreman;
import domain.Owner;

import javax.swing.*;
import java.util.List;

public class RegisterConstructionSite extends javax.swing.JFrame {

    private ConstructionsManagementSystem system1;
    private DefaultListModel<String> ownerListModel;
    private DefaultListModel<String> foremanListModel;
    
    public RegisterConstructionSite(ConstructionsManagementSystem system) {
        system1 = system;
        ownerListModel = new DefaultListModel<>();
        foremanListModel = new DefaultListModel<>();
        initComponents();
        loadOwnerList();
        loadForemanList();
    }
private void loadOwnerList() {
         ownerListModel.clear();
        List<Owner> owners = system1.obtainOwners();
        for (Owner owner : owners) {
            ownerListModel.addElement(owner.getName());
        }
        OwnerList.setModel(ownerListModel); // Ensure JList is updated
        System.out.println("Loaded owners: " + ownerListModel);
    }

    private void loadForemanList() {
          foremanListModel.clear();
        List<Foreman> foremen = system1.obtainForemen();
        for (Foreman foreman : foremen) {
            foremanListModel.addElement(foreman.getName());
        }
        ForemanList.setModel(foremanListModel); // Ensure JList is updated
        System.out.println("Loaded foremen: " + foremanListModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        OwnerListLabel = new javax.swing.JLabel();
        ForemanListLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OwnerList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ForemanList = new javax.swing.JList<>();
        PermitNumberLable = new javax.swing.JLabel();
        PermitNumberInput = new javax.swing.JTextField();
        AdressLabel = new javax.swing.JLabel();
        AdressInput = new javax.swing.JTextField();
        StartConstructionLabel = new javax.swing.JLabel();
        MonthInput = new javax.swing.JSpinner();
        YearsInput = new javax.swing.JSpinner();
        TotalBudgetLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TotalBudgetInput = new javax.swing.JTextPane();
        javax.swing.JButton AddButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Obra");
        setSize(new java.awt.Dimension(5, 5));
        getContentPane().setLayout(null);

        jLabel1.setText("Registro de Obra");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 100, 16);

        OwnerListLabel.setText("Propietarios");
        getContentPane().add(OwnerListLabel);
        OwnerListLabel.setBounds(20, 40, 70, 16);

        ForemanListLabel.setText("Capataces");
        getContentPane().add(ForemanListLabel);
        ForemanListLabel.setBounds(210, 40, 60, 16);

        OwnerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(OwnerList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 160, 146);

        ForemanList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ForemanList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(210, 60, 160, 146);

        PermitNumberLable.setText("Permiso Nro");
        getContentPane().add(PermitNumberLable);
        PermitNumberLable.setBounds(410, 30, 80, 16);

        PermitNumberInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermitNumberInputActionPerformed(evt);
            }
        });
        getContentPane().add(PermitNumberInput);
        PermitNumberInput.setBounds(410, 60, 64, 22);

        AdressLabel.setText("Dirección");
        getContentPane().add(AdressLabel);
        AdressLabel.setBounds(410, 100, 70, 16);

        AdressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdressInputActionPerformed(evt);
            }
        });
        getContentPane().add(AdressInput);
        AdressInput.setBounds(410, 130, 160, 22);

        StartConstructionLabel.setText("Comienzo Mes/Año");
        getContentPane().add(StartConstructionLabel);
        StartConstructionLabel.setBounds(410, 180, 110, 16);
        getContentPane().add(MonthInput);
        MonthInput.setBounds(410, 210, 64, 22);
        getContentPane().add(YearsInput);
        YearsInput.setBounds(490, 210, 64, 22);

        TotalBudgetLabel.setText("Total Presupuesto");
        getContentPane().add(TotalBudgetLabel);
        TotalBudgetLabel.setBounds(370, 250, 100, 16);

        jScrollPane3.setViewportView(TotalBudgetInput);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(490, 250, 64, 22);

        AddButton.setText("Agregar");
        AddButton.setToolTipText("");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AddButton);
        AddButton.setBounds(420, 380, 110, 23);

        setBounds(0, 0, 605, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void PermitNumberInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermitNumberInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermitNumberInputActionPerformed

    private void AdressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdressInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdressInputActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterConstructionSite(new ConstructionsManagementSystem()).setVisible(true);
            }
        });
    
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterConstructionSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterConstructionSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterConstructionSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterConstructionSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterConstructionSite(system1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdressInput;
    private javax.swing.JLabel AdressLabel;
    private javax.swing.JList<String> ForemanList;
    private javax.swing.JLabel ForemanListLabel;
    private javax.swing.JSpinner MonthInput;
    private javax.swing.JList<String> OwnerList;
    private javax.swing.JLabel OwnerListLabel;
    private javax.swing.JTextField PermitNumberInput;
    private javax.swing.JLabel PermitNumberLable;
    private javax.swing.JLabel StartConstructionLabel;
    private javax.swing.JTextPane TotalBudgetInput;
    private javax.swing.JLabel TotalBudgetLabel;
    private javax.swing.JSpinner YearsInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

}
