/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemGuis;

/**
 *
 * @author diego
 */
public class RegisterOwner extends javax.swing.JFrame {

    /**
     * Creates new form RegisterOwner
     */
    public RegisterOwner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterOwnerTitle = new javax.swing.JLabel();
        NameForemanInput = new javax.swing.JTextField();
        NameOwnerLabel = new javax.swing.JLabel();
        IdOwnerLabel = new javax.swing.JLabel();
        IdOwnerInput = new javax.swing.JTextField();
        AdressOwnerLabel = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        CellphoneOwnerLable = new javax.swing.JLabel();
        CellphoneOwnerInput = new javax.swing.JTextField();
        addOwnerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        RegisterOwnerTitle.setText("Registrar Propietario");
        getContentPane().add(RegisterOwnerTitle);
        RegisterOwnerTitle.setBounds(16, 16, 110, 16);
        getContentPane().add(NameForemanInput);
        NameForemanInput.setBounds(20, 70, 150, 22);

        NameOwnerLabel.setText("Nombre:");
        getContentPane().add(NameOwnerLabel);
        NameOwnerLabel.setBounds(20, 50, 60, 16);

        IdOwnerLabel.setText("Cédula de Identidad:");
        getContentPane().add(IdOwnerLabel);
        IdOwnerLabel.setBounds(20, 110, 130, 16);
        getContentPane().add(IdOwnerInput);
        IdOwnerInput.setBounds(20, 130, 150, 22);

        AdressOwnerLabel.setText("Dirección:");
        getContentPane().add(AdressOwnerLabel);
        AdressOwnerLabel.setBounds(200, 50, 60, 16);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(200, 70, 160, 22);

        CellphoneOwnerLable.setText("Celular");
        getContentPane().add(CellphoneOwnerLable);
        CellphoneOwnerLable.setBounds(200, 110, 100, 16);
        getContentPane().add(CellphoneOwnerInput);
        CellphoneOwnerInput.setBounds(200, 130, 160, 22);

        addOwnerButton.setText("Agregar");
        addOwnerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOwnerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addOwnerButton);
        addOwnerButton.setBounds(20, 180, 110, 23);

        setBounds(0, 0, 414, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void addOwnerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOwnerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addOwnerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterOwner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterOwner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdressOwnerLabel;
    private javax.swing.JTextField CellphoneOwnerInput;
    private javax.swing.JLabel CellphoneOwnerLable;
    private javax.swing.JTextField IdOwnerInput;
    private javax.swing.JLabel IdOwnerLabel;
    private javax.swing.JTextField NameForemanInput;
    private javax.swing.JLabel NameOwnerLabel;
    private javax.swing.JLabel RegisterOwnerTitle;
    private javax.swing.JButton addOwnerButton;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
